#http
POST http://127.0.0.1:5000/api/wilder
Content-Type: application/json

{
  "name":"Jane Doe11",
  "city":"Lyon",
  "skills":[
    { "title": "HTML1", "count": 10 },
    { "title": "React", "count": 5 }
  ]
}
###

#http
GET http://127.0.0.1:5000/api/wilder
###

#http
PUT http://127.0.0.1:5000/api/wilder
content-type: application/json

{
  "_id": "5fa1c6f9a2a561470e7eebf9",
  "name":"A new name",
  "city": "Londres",
  "skills":[
    {"title":"express", "votes":5},
    {"title":"mongo", "votes":12}
  ]
}
###

#http
DELETE http://127.0.0.1:5000/api/wilder
content-type: application/json

{
  "_id": "5faa6fcf1ae69f66d76ee18b"
}